"""crear esquema inicial del MVP"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "d5afc0f6a48c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorias",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("categoria_padre_id", sa.UUID(), nullable=True),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column(
            "esta_activo", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["categoria_padre_id"],
            ["categorias.id"],
            name="fk_categorias_padre",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_categorias_slug"),
    )
    op.create_table(
        "definiciones_especificacion",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("unidad", sa.String(length=40), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_definiciones_especificacion_slug"),
    )
    op.create_table(
        "marcas",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column(
            "esta_activo", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre", name="uq_marcas_nombre"),
        sa.UniqueConstraint("slug", name="uq_marcas_slug"),
    )
    op.create_table(
        "metodos_pago",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column(
            "esta_activo", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo", name="uq_metodos_pago_codigo"),
        sa.UniqueConstraint("nombre", name="uq_metodos_pago_nombre"),
    )
    op.create_table(
        "roles",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column(
            "esta_activo", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo", name="uq_roles_codigo"),
        sa.UniqueConstraint("nombre", name="uq_roles_nombre"),
    )
    op.create_table(
        "productos",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("categoria_id", sa.UUID(), nullable=False),
        sa.Column("marca_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("precio", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "existencias", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "esta_activo", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "existencias >= 0", name="ck_productos_existencias_no_negativas"
        ),
        sa.CheckConstraint("precio >= 0", name="ck_productos_precio_no_negativo"),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
            name="fk_productos_categoria",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["marca_id"], ["marcas.id"], name="fk_productos_marca", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_productos_slug"),
    )
    op.create_index(
        "ix_productos_categoria_id", "productos", ["categoria_id"], unique=False
    )
    op.create_index("ix_productos_marca_id", "productos", ["marca_id"], unique=False)
    op.create_index("ix_productos_nombre", "productos", ["nombre"], unique=False)
    op.create_index("ix_productos_precio", "productos", ["precio"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("rol_id", sa.UUID(), nullable=False),
        sa.Column("correo_electronico", sa.String(length=320), nullable=False),
        sa.Column("nombre_completo", sa.String(length=150), nullable=False),
        sa.Column("hash_contrasena", sa.String(length=255), nullable=True),
        sa.Column(
            "esta_activo", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rol_id"], ["roles.id"], name="fk_usuarios_rol", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "correo_electronico", name="uq_usuarios_correo_electronico"
        ),
    )
    op.create_index("ix_usuarios_rol_id", "usuarios", ["rol_id"], unique=False)
    op.create_table(
        "carritos",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name="fk_carritos_usuario",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("usuario_id", name="uq_carritos_usuario_id"),
    )
    op.create_table(
        "cuentas_oauth",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("proveedor", sa.String(length=50), nullable=False),
        sa.Column("identificador_proveedor", sa.String(length=255), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name="fk_cuentas_oauth_usuario",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "proveedor",
            "identificador_proveedor",
            name="uq_cuentas_oauth_proveedor_identificador",
        ),
        sa.UniqueConstraint(
            "usuario_id", "proveedor", name="uq_cuentas_oauth_usuario_proveedor"
        ),
    )
    op.create_table(
        "especificaciones_producto",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("definicion_especificacion_id", sa.UUID(), nullable=False),
        sa.Column("valor", sa.String(length=255), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["definicion_especificacion_id"],
            ["definiciones_especificacion.id"],
            name="fk_especificaciones_producto_definicion",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name="fk_especificaciones_producto_producto",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "producto_id",
            "definicion_especificacion_id",
            name="uq_especificaciones_producto",
        ),
    )
    op.create_table(
        "favoritos",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name="fk_favoritos_producto",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name="fk_favoritos_usuario",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "usuario_id", "producto_id", name="uq_favoritos_usuario_producto"
        ),
    )
    op.create_table(
        "imagenes_producto",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("texto_alternativo", sa.String(length=255), nullable=True),
        sa.Column(
            "orden", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("orden >= 0", name="ck_imagenes_producto_orden_no_negativo"),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name="fk_imagenes_producto_producto",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("producto_id", "orden", name="uq_imagenes_producto_orden"),
    )
    op.create_table(
        "pedidos",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("metodo_pago_id", sa.UUID(), nullable=False),
        sa.Column(
            "estado",
            postgresql.ENUM(
                "pendiente",
                "confirmado",
                "en_preparacion",
                "enviado",
                "entregado",
                "cancelado",
                name="estado_pedido",
            ),
            server_default=sa.text("'pendiente'"),
            nullable=False,
        ),
        sa.Column("moneda", sa.CHAR(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "importe_envio",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("destinatario_envio", sa.String(length=150), nullable=False),
        sa.Column("telefono_envio", sa.String(length=40), nullable=False),
        sa.Column("direccion_envio_linea_1", sa.String(length=255), nullable=False),
        sa.Column("direccion_envio_linea_2", sa.String(length=255), nullable=True),
        sa.Column("ciudad_envio", sa.String(length=120), nullable=False),
        sa.Column("region_envio", sa.String(length=120), nullable=False),
        sa.Column("codigo_postal_envio", sa.String(length=20), nullable=True),
        sa.Column("codigo_pais_envio", sa.CHAR(length=2), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "importe_envio >= 0", name="ck_pedidos_importe_envio_no_negativo"
        ),
        sa.CheckConstraint("subtotal >= 0", name="ck_pedidos_subtotal_no_negativo"),
        sa.CheckConstraint(
            "total = subtotal + importe_envio", name="ck_pedidos_total_consistente"
        ),
        sa.CheckConstraint("total >= 0", name="ck_pedidos_total_no_negativo"),
        sa.ForeignKeyConstraint(
            ["metodo_pago_id"],
            ["metodos_pago.id"],
            name="fk_pedidos_metodo_pago",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name="fk_pedidos_usuario",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pedidos_creado_en", "pedidos", ["creado_en"], unique=False)
    op.create_index("ix_pedidos_estado", "pedidos", ["estado"], unique=False)
    op.create_index(
        "ix_pedidos_metodo_pago_id", "pedidos", ["metodo_pago_id"], unique=False
    )
    op.create_index("ix_pedidos_usuario_id", "pedidos", ["usuario_id"], unique=False)
    op.create_table(
        "detalles_carrito",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("carrito_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column(
            "cantidad", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cantidad > 0", name="ck_detalles_carrito_cantidad_positiva"
        ),
        sa.ForeignKeyConstraint(
            ["carrito_id"],
            ["carritos.id"],
            name="fk_detalles_carrito_carrito",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name="fk_detalles_carrito_producto",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "carrito_id", "producto_id", name="uq_detalles_carrito_producto"
        ),
    )
    op.create_table(
        "detalles_pedido",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("pedido_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=True),
        sa.Column("nombre_producto", sa.String(length=200), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cantidad > 0", name="ck_detalles_pedido_cantidad_positiva"),
        sa.CheckConstraint(
            "precio_unitario >= 0", name="ck_detalles_pedido_precio_no_negativo"
        ),
        sa.CheckConstraint(
            "subtotal = precio_unitario * cantidad",
            name="ck_detalles_pedido_subtotal_consistente",
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
            name="fk_detalles_pedido_pedido",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name="fk_detalles_pedido_producto",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_detalles_pedido_pedido_id", "detalles_pedido", ["pedido_id"], unique=False
    )
    op.create_index(
        "ix_detalles_pedido_producto_id",
        "detalles_pedido",
        ["producto_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_detalles_pedido_producto_id", table_name="detalles_pedido")
    op.drop_index("ix_detalles_pedido_pedido_id", table_name="detalles_pedido")
    op.drop_table("detalles_pedido")
    op.drop_table("detalles_carrito")
    op.drop_index("ix_pedidos_usuario_id", table_name="pedidos")
    op.drop_index("ix_pedidos_metodo_pago_id", table_name="pedidos")
    op.drop_index("ix_pedidos_estado", table_name="pedidos")
    op.drop_index("ix_pedidos_creado_en", table_name="pedidos")
    op.drop_table("pedidos")
    op.drop_table("imagenes_producto")
    op.drop_table("favoritos")
    op.drop_table("especificaciones_producto")
    op.drop_table("cuentas_oauth")
    op.drop_table("carritos")
    op.drop_index("ix_usuarios_rol_id", table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index("ix_productos_precio", table_name="productos")
    op.drop_index("ix_productos_nombre", table_name="productos")
    op.drop_index("ix_productos_marca_id", table_name="productos")
    op.drop_index("ix_productos_categoria_id", table_name="productos")
    op.drop_table("productos")
    op.drop_table("roles")
    op.drop_table("metodos_pago")
    op.drop_table("marcas")
    op.drop_table("definiciones_especificacion")
    op.drop_table("categorias")
    postgresql.ENUM(name="estado_pedido").drop(op.get_bind())
    # ### end Alembic commands ###
